# Welcome to Jekyll!
#

# Site settings
title: Brain Image Library
description: A repository for confocal microscopy images of brain tissue
owner: Pittsburgh Supercomputing Center # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: bil-support@psc.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brain-image-library.github.io" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/brain-image-library
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
